<a href="https://colab.research.google.com/github/kahuroA/SQL-PRACTICE/blob/main/Copy_of_SQL_Programming_Inserting_%26_Updating_Data_with_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Inserting and Updating Data with SQL

## 1.1 Let's first connect to our Database

In [2]:
# We will first load the sql extension into our environment
%load_ext sql

# Then connect to our in memory sqlite database
# NB: This database will cease to exist as soon as the database connection is closed. 
%sql sqlite://

'Connected: @None'

## 1.2 Importing Data From CSV Files

In [3]:
# In order to read any csv file, we will need to import our python csv library
# This will allow us to read a csv file that we will have uploaded to our evironment
import csv

In [4]:
# We will also need a pandas library which is used for data manipulation in this notebook. For now, don't worry too much about how it functions, we will explore it in details in the coming weeks.
import pandas as pd

Then we will download our csv files from 
*   [Interpol Dataset](http://bit.ly/DSInterpol) 
*   [Startups Dataset](http://bit.ly/DSStartup)
*   [Transactions Dataset](http://bit.ly/DSTransactions)
*   [Glass Dataset](http://bit.ly/DSGlass)

Later upload them to our current environment on Colaboratory by clicking View > Table of Contents > Files then Upload.  
(We should not load these files from url)

In [5]:
# Upon uploading our file, we will then load our first table from the CSV file as shown 
# We are going to use one of pandas function which is read_csv(). This function helps us to load data from csv files into python. It takes a several arguments/ parameters but we are going to use only a few for now. 
# The first arugument is the path of the csv file. This tells the function where your csv is located and the name of the csv. It can also be a url.
# The second argument, index_col, tells pandas to use the row indexes as the row labels.
with open('./sample_data/Interpol.csv','r') as f:
    Interpol = pd.read_csv(f, index_col=0, encoding='utf-8')

In [6]:
# We will then drop existing tables similar to the one that we will work with
# in our current sqlite environment. Then push our Interpol data into a new 
# table within our current SQLite Database 
#
%sql DROP TABLE if EXISTS Interpol;
%sql PERSIST Interpol;

 * sqlite://
Done.
 * sqlite://

'Persisted interpol'

In [7]:
# Previewing our Interpol table
#
%%sql
SELECT * FROM Interpol LIMIT 5;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif')]

### <font color="green">1.2 Challenges</font>

In [8]:
# Challenge 1
# Let's load our Startups.csv file. 
# Feel free to copy paste the code above and make the necessary modifications
# 
with open('./sample_data/Startups.csv','r') as f:
  start_ups=pd.read_csv(f, index_col=0, encoding='utf-8' )

In [9]:
%sql DROP TABLE IF EXISTS start_ups;
%sql PERSIST start_ups;

 * sqlite://
Done.
 * sqlite://

'Persisted start_ups'

In [10]:
# Challenge 2
# Let's load our Transactions.csv file below
# 
with open('./sample_data/Transactions.csv','r') as f:
  transact=pd.read_csv(f, index_col=0, encoding='utf-8' )

In [11]:
%sql DROP TABLE IF EXISTS transact;
%sql PERSIST transact;

 * sqlite://
Done.
 * sqlite://

'Persisted transact'

In [38]:
# Challenge 3
# Let's load our Glass.csv file below
# 
with open('./sample_data/Glass.csv','r') as f:
  glass=pd.read_csv(f, index_col=0, encoding='utf-8' )

In [39]:
%sql DROP TABLE IF EXISTS glass;
%sql PERSIST glass;

 * sqlite://
Done.
 * sqlite://

'Persisted glass'

## 1.3 Inserting data into a table

In [12]:
# Example 1: Previewing our table 
# We will first preview the last 5 records in Interpol our table
# NB: We learn this in our last SQL Session i.e. Sorting
#
%%sql
SELECT * FROM Interpol LIMIT 5;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif')]

In [13]:
# Example 2: Inserting data
# Then we will insert new data into our table and noting the added record
# Country = Uganda
# National Fugitives = 1
# Wanted Fugitives = 1
# Possible Hosted Fugitives / Captured Fugitives = 0
# Region = Sub Saharan Africa
# Flag = https://www.crwflags.com/art/countries/uganda.gif
%%sql
INSERT INTO Interpol (Country, "National Fugitives", "Wanted Fugitives", "Possible Hosted Fugitives / Captured Fugitives", Region, Flag)
VALUES ('Uganda', '1', '1', '0', 'Sub Saharan Africa', 'https://www.crwflags.com/art/countries/uganda.gif');

SELECT * FROM Interpol ORDER BY Country DESC LIMIT 5;

 * sqlite://
1 rows affected.
Done.

[('Zimbabwe', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif'),
 ('Zambia', 1, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Venezuela', 0, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Uruguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('United States', 8, 11, 6, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif')]

In [14]:
# Example 2: Previewing the first five records in the Startups.csv file
#
%%sql 
SELECT * FROM Start_ups LIMIT 5;

 * sqlite://
Done.

[('Curebit', 'Operating', 2010.0, 'San Francisco - California - USA', 'Talkable is a social referral platform for online stories and subscriptions.', 'E-Commerce, Analytics, Internet, Marketing, Social Media', 'Allan Grant, Dominic Coryell, Jeff Yee, Nori Yoshida', 2011, 'Winter', '500 Startups, Dharmesh Shah, Alex Lloyd, Auren Hoffman, Gordon Tucker, Stage One Capital, reinmkr inc., Karl Jacob, Y Combinator', '$1200000, undisclosed amount', '290 Division St, #405, San Francisco, California, USA', 'San Francisco', 'California', 'USA', 'http://a5.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1407434890/sf19b2lsipbo6fazmjzq.png', 'http://www.seed-db.com/companies/view?companyid=102020', 'http://www.crunchbase.com/organization/curebit', 'https://www.talkable.com'),
 ('Goldbely', 'Operating', None, 'San Francisco - California - USA', "Goldbely is an e-commerce site for buying and discovering America's best handmade gourmet food & gifts.", 'Social, E-Commerce', 'Joe Ariel, Joel Gillman, Trevor Stow, Vanessa Torrivilla', 2013, 'Winter', '500 Startups, Funders Club, Dave McClure, Tim Draper, Intel Capital, ACE & Company, Y Combinator', '$3,000,000', '1 Bluxome Street, San Francisco, California, USA', 'San Francisco', 'California', 'USA', 'http://a3.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397180367/99717257bb2a360419f75b586503af93.png', 'http://www.seed-db.com/companies/view?companyid=729001', 'http://www.crunchbase.com/organization/goldbely', 'http://www.goldbely.com'),
 ('theDailyMuse', 'Operating', 2011.0, 'New York City - New York - USA', 'The Daily Muse is a job search platform offering multimedia profiles of various companies that are hiring people.', None, 'Alex Cavoulacos, Kathryn Minshew, Melissa McCreery', 2012, 'Winter', '500 Startups, Great Oaks Venture Capital, Great Oaks Venture Capital, Thomas D. Lehrman, Adam Quinton, Y Combinator', '$2800000, $2100000, $1200000, $1200000', '33 WEST 26TH STREET, #2, New York, New York, USA', 'New York City', 'New York', 'USA', 'http://a5.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1398232938/ffck9mcohrtktbkj3oie.jpg', 'http://www.seed-db.com/companies/view?companyid=96040', 'http://www.crunchbase.com/organization/the-daily-muse', 'http://www.thedailymuse.com'),
 ('Zencoder', 'Exited', None, 'San Francisco - California - USA', 'Zencoder is web-based video encoding SaaS designed to convert any video into web and mobile-compatible formats in real-time.', 'SaaS, Cloud Computing, Audio, Web Development, Data, Security, Video, Software', 'Brandon Arbini, Jon Dahl, Steve Heffernan', 2010, 'Winter', '500 Startups, Matt Cutts, Ignition Partners, James Lindenbaum, Orion Henry, Neil McClements, Wolfgang Buehler, Justin Yoshimura, Mike Bollinger, Adam Wiggins, SV Angel, Founder Collective, Robert Weber, Lowercase Capital, Andreessen Horowitz, Y Combinator', '$2000000, undisclosed amount', 'San Francisco, CA, 94103, USA', 'San Francisco', 'California', 'USA', 'http://a1.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397206653/62e91e3f1c95f92912be5bd26638ea60.png', 'http://www.seed-db.com/companies/view?companyid=98019', 'http://www.crunchbase.com/organization/zencoder', 'http://zencoder.com'),
 ('GinzaMetrics', 'Operating', None, 'San Francisco - California - USA', 'GinzaMetrics offers an SEO and content marketing platform that provides recommendations and competitor analytics to agencies and marketers.', 'Enterprises, E-Commerce, Analytics, SEO, Enterprise Software', 'Ray Grieselhuber', 2010, 'Summer', '500 Startups, 500 Startups, Venture51, Jeff Miller, SunBridge Global Ventures, Y Combinator', 'undisclosed amount, $1300000, $400000, $14000', '25 Taylor Street, San Francisco, CA, 94103, USA', 'San Francisco', 'California', 'USA', 'http://a2.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397186693/0738a0a8a1cce45f209ec0b0cbc75627.png', 'http://www.seed-db.com/companies/view?companyid=103018', 'http://www.crunchbase.com/organization/ginzametrics', 'http://ginzametrics.com')]

In [15]:
# Example 2: Inserting data
# Then we will insert new data into our table and noting all the values of the added record
# We will add The follwoing
# Company = 'Glova'
# Satus = 'Operating'   
# 
%%sql
INSERT INTO Start_ups (Company, Satus)
VALUES ('Glova', 'Operating');

SELECT * FROM Start_ups LIMIT 5;

 * sqlite://
1 rows affected.
Done.

[('Curebit', 'Operating', 2010.0, 'San Francisco - California - USA', 'Talkable is a social referral platform for online stories and subscriptions.', 'E-Commerce, Analytics, Internet, Marketing, Social Media', 'Allan Grant, Dominic Coryell, Jeff Yee, Nori Yoshida', 2011, 'Winter', '500 Startups, Dharmesh Shah, Alex Lloyd, Auren Hoffman, Gordon Tucker, Stage One Capital, reinmkr inc., Karl Jacob, Y Combinator', '$1200000, undisclosed amount', '290 Division St, #405, San Francisco, California, USA', 'San Francisco', 'California', 'USA', 'http://a5.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1407434890/sf19b2lsipbo6fazmjzq.png', 'http://www.seed-db.com/companies/view?companyid=102020', 'http://www.crunchbase.com/organization/curebit', 'https://www.talkable.com'),
 ('Goldbely', 'Operating', None, 'San Francisco - California - USA', "Goldbely is an e-commerce site for buying and discovering America's best handmade gourmet food & gifts.", 'Social, E-Commerce', 'Joe Ariel, Joel Gillman, Trevor Stow, Vanessa Torrivilla', 2013, 'Winter', '500 Startups, Funders Club, Dave McClure, Tim Draper, Intel Capital, ACE & Company, Y Combinator', '$3,000,000', '1 Bluxome Street, San Francisco, California, USA', 'San Francisco', 'California', 'USA', 'http://a3.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397180367/99717257bb2a360419f75b586503af93.png', 'http://www.seed-db.com/companies/view?companyid=729001', 'http://www.crunchbase.com/organization/goldbely', 'http://www.goldbely.com'),
 ('theDailyMuse', 'Operating', 2011.0, 'New York City - New York - USA', 'The Daily Muse is a job search platform offering multimedia profiles of various companies that are hiring people.', None, 'Alex Cavoulacos, Kathryn Minshew, Melissa McCreery', 2012, 'Winter', '500 Startups, Great Oaks Venture Capital, Great Oaks Venture Capital, Thomas D. Lehrman, Adam Quinton, Y Combinator', '$2800000, $2100000, $1200000, $1200000', '33 WEST 26TH STREET, #2, New York, New York, USA', 'New York City', 'New York', 'USA', 'http://a5.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1398232938/ffck9mcohrtktbkj3oie.jpg', 'http://www.seed-db.com/companies/view?companyid=96040', 'http://www.crunchbase.com/organization/the-daily-muse', 'http://www.thedailymuse.com'),
 ('Zencoder', 'Exited', None, 'San Francisco - California - USA', 'Zencoder is web-based video encoding SaaS designed to convert any video into web and mobile-compatible formats in real-time.', 'SaaS, Cloud Computing, Audio, Web Development, Data, Security, Video, Software', 'Brandon Arbini, Jon Dahl, Steve Heffernan', 2010, 'Winter', '500 Startups, Matt Cutts, Ignition Partners, James Lindenbaum, Orion Henry, Neil McClements, Wolfgang Buehler, Justin Yoshimura, Mike Bollinger, Adam Wiggins, SV Angel, Founder Collective, Robert Weber, Lowercase Capital, Andreessen Horowitz, Y Combinator', '$2000000, undisclosed amount', 'San Francisco, CA, 94103, USA', 'San Francisco', 'California', 'USA', 'http://a1.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397206653/62e91e3f1c95f92912be5bd26638ea60.png', 'http://www.seed-db.com/companies/view?companyid=98019', 'http://www.crunchbase.com/organization/zencoder', 'http://zencoder.com'),
 ('GinzaMetrics', 'Operating', None, 'San Francisco - California - USA', 'GinzaMetrics offers an SEO and content marketing platform that provides recommendations and competitor analytics to agencies and marketers.', 'Enterprises, E-Commerce, Analytics, SEO, Enterprise Software', 'Ray Grieselhuber', 2010, 'Summer', '500 Startups, 500 Startups, Venture51, Jeff Miller, SunBridge Global Ventures, Y Combinator', 'undisclosed amount, $1300000, $400000, $14000', '25 Taylor Street, San Francisco, CA, 94103, USA', 'San Francisco', 'California', 'USA', 'http://a2.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397186693/0738a0a8a1cce45f209ec0b0cbc75627.png', 'http://www.seed-db.com/companies/view?companyid=103018', 'http://www.crunchbase.com/organization/ginzametrics', 'http://ginzametrics.com')]

In [16]:
# Example 3
# Now Inserting a new record into the specific columns; Company, Mapping Location, Categories
# Company = "Moringa"
# Mapping Location = "Nairobi"
# Categories = "Education"
#
%%sql
INSERT INTO Start_ups (Company, "Mapping Location", Categories) 
VALUES ("Moringa", "Nairobi", "Education");

SELECT * FROM Start_ups LIMIT 2;

 * sqlite://
1 rows affected.
Done.

[('Curebit', 'Operating', 2010.0, 'San Francisco - California - USA', 'Talkable is a social referral platform for online stories and subscriptions.', 'E-Commerce, Analytics, Internet, Marketing, Social Media', 'Allan Grant, Dominic Coryell, Jeff Yee, Nori Yoshida', 2011, 'Winter', '500 Startups, Dharmesh Shah, Alex Lloyd, Auren Hoffman, Gordon Tucker, Stage One Capital, reinmkr inc., Karl Jacob, Y Combinator', '$1200000, undisclosed amount', '290 Division St, #405, San Francisco, California, USA', 'San Francisco', 'California', 'USA', 'http://a5.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1407434890/sf19b2lsipbo6fazmjzq.png', 'http://www.seed-db.com/companies/view?companyid=102020', 'http://www.crunchbase.com/organization/curebit', 'https://www.talkable.com'),
 ('Goldbely', 'Operating', None, 'San Francisco - California - USA', "Goldbely is an e-commerce site for buying and discovering America's best handmade gourmet food & gifts.", 'Social, E-Commerce', 'Joe Ariel, Joel Gillman, Trevor Stow, Vanessa Torrivilla', 2013, 'Winter', '500 Startups, Funders Club, Dave McClure, Tim Draper, Intel Capital, ACE & Company, Y Combinator', '$3,000,000', '1 Bluxome Street, San Francisco, California, USA', 'San Francisco', 'California', 'USA', 'http://a3.images.crunchbase.com/image/upload/c_pad,h_98,w_98/v1397180367/99717257bb2a360419f75b586503af93.png', 'http://www.seed-db.com/companies/view?companyid=729001', 'http://www.crunchbase.com/organization/goldbely', 'http://www.goldbely.com')]

### <font color="green">1.3 Challenges</font>

In [17]:
# Challenge 1
# Insert a new record into the Interpol table with  
# Country = Tanzania
# National Fugitives = 3
# Wanted Fugitives = Null
# Possible Hosted Fugitives / Captured Fugitives = 2
# Region = Sub Saharan Africa
# Flag = https://www.crwflags.com/art/countries/tanzania.gif
# 
%%sql
INSERT into Interpol(Country, "National Fugitives", "Wanted Fugitives", "Possible Hosted Fugitives / Captured Fugitives",Region, Flag)
VALUES('Tanzania',3,Null,2 ,'Sub Saharan Africa','https://www.crwflags.com/art/countries/tanzania.gif');

SELECT * FROM Interpol WHERE Interpol.Country='Tanzania';

 * sqlite://
1 rows affected.
Done.

[('Tanzania', 0, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif'),
 ('Tanzania', 3, None, 2, 'Sub Saharan Africa', 'https://www.crwflags.com/art/countries/tanzania.gif')]

In [18]:
# Challenge 2
# Insert any two records of your choosing into the Interpol table
# 
%%sql

INSERT into Interpol(Country, "National Fugitives", "Wanted Fugitives", "Possible Hosted Fugitives / Captured Fugitives",Region, Flag)
VALUES('Botswana',30,6,2 ,'Sub Saharan Africa','https://www.crwflags.com/art/countries/botswana.gif'), ('Sudan',300,16,21 ,'Sub Saharan Africa','https://www.crwflags.com/art/countries/sudan.gif');

 * sqlite://
2 rows affected.

[]

In [19]:
# Challenge 3
# Insert any new record in the Startups table only have the following attributes 
# Company, Mapping Location, Categories
# 
%%sql

INSERT into Start_ups(Company, 'Mapping Location','Categories') VALUES('United Stand','London','Sport Analysis');

 * sqlite://
1 rows affected.

[]

## 1.4 Updating records in a table

In [20]:
# Example 1
# Let's update Albania to 4 National Fugitives in the Interpol table.
# 
%%sql
UPDATE Interpol
SET "National Fugitives" = 4
WHERE Country = "Albania";

SELECT * FROM Interpol WHERE Interpol.Country='Albania';

 * sqlite://
1 rows affected.
Done.

[('Albania', 4, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif')]

In [21]:
# Example 2
# Let's update any transactions record that has ride_id = 5781 
# to 5782
#
%%sql
UPDATE Transact
SET ride_id = 5782
WHERE ride_id = 5781;

SELECT * FROM Transact  where Transact.ride_id=5782 ;

 * sqlite://
3 rows affected.
Done.

[(5782, '22A', 'Mpesa', 'VGG7Q3MVJX', '27-11-17', '7:09', 'Homa Bay', 'Nairobi', 'Bus', 49),
 (5782, '18B', 'Mpesa', 'YJ7JFHOGKA', '27-11-17', '7:09', 'Homa Bay', 'Nairobi', 'Bus', 49),
 (5782, '17B', 'Mpesa', '4JQOSC881A', '27-11-17', '7:09', 'Homa Bay', 'Nairobi', 'Bus', 49)]

In [22]:
# Example 3
# Let's update the transactions record with ride_id = 5778 to 
# have travel_from = 'Kisii' and car_type = 'shuttle'
#
%%sql
UPDATE Transact
SET travel_from = 'Kisii', car_type = 'shuttle'
WHERE ride_id = 5778;

SELECT * FROM Transact WHERE Transact.ride_id=5778;

 * sqlite://
4 rows affected.
Done.

[(5778, '11A', 'Mpesa', 'BM97HFRGL9', '27-11-17', '7:12', 'Kisii', 'Nairobi', 'shuttle', 49),
 (5778, '25', 'Mpesa', 'MYVTYFNXDZ', '27-11-17', '7:12', 'Kisii', 'Nairobi', 'shuttle', 49),
 (5778, '21B', None, 'TE1WYK1NYE', '27-11-17', '7:12', 'Kisii', 'Nairobi', 'shuttle', 49),
 (5778, '3A', 'Mpesa', 'JDD4ZL64LP', '27-11-17', '7:12', 'Kisii', 'Nairobi', 'shuttle', 49)]

### <font color="green">1.4 Challenges</font>

In [53]:
# Challenge 1
# Update the transactions records with the 
# payment_method = none to Null
# 
%%sql
UPDATE Transact 
SET "payment_method" =Null 
WHERE "payment_method" ='None';

SELECT payment_method FROM Transact;

 * sqlite://
2 rows affected.
Done.

[('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 (None,),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 (None,),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',)]

In [ ]:
%%sql
SELECT payment_method FROM Transact

 * sqlite://
Done.

[('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 (None,),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',),
 (None,),
 ('Mpesa',),
 ('Mpesa',),
 ('Mpesa',)]

In [30]:
# Challenge 2
# Update the Interpol records with Wanted Fugitives	 = 2
# to National Fugitives = 2 
# 
%%sql
UPDATE Interpol SET "National Fugitives"=2 WHERE "Wanted Fugitives"=2;

 * sqlite://
12 rows affected.

[]

In [32]:
# Challenge 3 
# Update the transactions records with car_type = "Bus" to 
# have car_type = "shuttle" and travel_to = "Nairobi Downtown"
# 
%%sql
UPDATE transact SET "car_type"='shuttle' WHERE "car_type"='Bus';

 * sqlite://
11 rows affected.

[]

## 1.5 Updating with Conditions

In [34]:
# Example 1
# As you have seen from the previous examples, we used the WHERE clause to specify
# where we would like to make our updates on the table.
# Now, how then would we do this for multiple records. Say, we wanted to update 
# records with Kisii to "Kisii Old Stage", we would do the following
#
%%sql 
UPDATE Transact
SET travel_from = "Old Kisii"
WHERE travel_from = "Kisii";

SELECT * FROM Transact;

 * sqlite://
12 rows affected.
Done.

[(1442, '15A', 'Mpesa', 'UZUEHCBUSO', '17-10-17', '7:15', 'Migori', 'Nairobi', 'shuttle', 49),
 (5437, '14A', 'Mpesa', 'TIHLBUSGTE', '19-11-17', '7:12', 'Migori', 'Nairobi', 'shuttle', 49),
 (5710, '8B', 'Mpesa', 'EQX8Q5G19O', '26-11-17', '7:05', 'Keroka', 'Nairobi', 'shuttle', 49),
 (5777, '19A', 'Mpesa', 'SGP18CL0ME', '27-11-17', '7:10', 'Homa Bay', 'Nairobi', 'shuttle', 49),
 (5778, '11A', 'Mpesa', 'BM97HFRGL9', '27-11-17', '7:12', 'Old Kisii', 'Nairobi', 'shuttle', 49),
 (5777, '18B', 'Mpesa', 'B6PBDU30IZ', '27-11-17', '7:10', 'Homa Bay', 'Nairobi', 'shuttle', 49),
 (5777, '14A', 'Mpesa', 'MZHGDGS6QZ', '27-11-17', '7:10', 'Homa Bay', 'Nairobi', 'shuttle', 49),
 (5778, '25', 'Mpesa', 'MYVTYFNXDZ', '27-11-17', '7:12', 'Old Kisii', 'Nairobi', 'shuttle', 49),
 (5778, '21B', None, 'TE1WYK1NYE', '27-11-17', '7:12', 'Old Kisii', 'Nairobi', 'shuttle', 49),
 (5782, '22A', 'Mpesa', 'VGG7Q3MVJX', '27-11-17', '7:09', 'Homa Bay', 'Nairobi', 'shuttle', 49),
 (5782, '18B', 'Mpesa', 'YJ7JFHOGKA', '27-11-17', '7:09', 'Homa Bay', 'Nairobi', 'shuttle', 49),
 (5782, '17B', 'Mpesa', '4JQOSC881A', '27-11-17', '7:09', 'Homa Bay', 'Nairobi', 'shuttle', 49),
 (5784, '1X', 'Mpesa', '3OPU23FHRB', '20-04-18', '5:10', 'Old Kisii', 'Nairobi', 'shuttle', 11),
 (5789, '1X', 'Mpesa', 'BPRX4UMFFN', '20-04-18', '9:50', 'Old Kisii', 'Nairobi', 'shuttle', 11),
 (5778, '3A', 'Mpesa', 'JDD4ZL64LP', '27-11-17', '7:12', 'Old Kisii', 'Nairobi', 'shuttle', 49),
 (5790, '1B', 'Mpesa', 'DC8ABRSXXK', '20-04-18', '7:06', 'Old Kisii', 'Nairobi', 'shuttle', 49),
 (5791, '1', 'Mpesa', 'HGQURN0SZS', '20-04-18', '6:00', 'Old Kisii', 'Nairobi', 'shuttle', 11),
 (5792, '1', None, '8D9V8HK2FC', '20-04-18', '5:50', 'Old Kisii', 'Nairobi', 'shuttle', 11),
 (5793, '1', 'Mpesa', 'TTZQDYZHAB', '20-04-18', '10:58', 'Old Kisii', 'Nairobi', 'shuttle', 11),
 (5790, '4A', 'Mpesa', 'F8VBKYCXPL', '20-04-18', '7:06', 'Old Kisii', 'Nairobi', 'shuttle', 49),
 (5794, '1', 'Mpesa', 'ETNVCDEZLR', '20-04-18', '6:50', 'Old Kisii', 'Nairobi', 'shuttle', 11)]

In [ ]:
# Example 2
# We also need to be careful when updating records. If we omit the WHERE clause, ALL records will be updated!
# For example, running the code below will update our entire Wanted Fugitives 
# column with our new value as show in this example
# 
%%sql
UPDATE Interpol
SET "Wanted Fugitives"= 1; 

SELECT * FROM Interpol;

In [ ]:
# Example 2: Getting back our values.
# A way to get back our values in the Wanted Fugitives table
# is to read the table again. However, this will not consider any changes
# that we had made earlier on.
with open('Interpol.csv','r') as f:
    Interpol = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE if EXISTS Interpol;
%sql PERSIST Interpol;
%sql SELECT * from Interpol;

In [40]:
# Example 3
# We can update Glass records which have Fe > 2.5 to Type = 2 
# We first preview it below
#
%%sql
SELECT * FROM glass;

 * sqlite://
Done.

[(1.52101, 13.64, 4.49, 1.1, 71.78, 0.06, 8.75, 0.0, 0.0, 1),
 (1.5176100000000001, 13.89, 3.6, 1.36, 72.73, 0.48, 7.83, 0.0, 0.0, 1),
 (1.5161799999999999, 13.53, 3.55, 1.54, 72.99, 0.39, 7.78, 0.0, 0.0, 1),
 (1.51766, 13.21, 3.69, 1.29, 72.61, 0.57, 8.22, 0.0, 0.0, 1),
 (1.51742, 13.27, 3.62, 1.24, 73.08, 0.55, 8.07, 0.0, 0.0, 1),
 (1.51596, 12.79, 3.61, 1.62, 72.97, 0.64, 8.07, 0.0, 0.26, 1),
 (1.5174299999999998, 13.3, 3.6, 1.14, 73.09, 0.58, 8.17, 0.0, 0.0, 1),
 (1.51756, 13.15, 3.61, 1.05, 73.24, 0.57, 8.24, 0.0, 0.0, 1),
 (1.51918, 14.04, 3.58, 1.37, 72.08, 0.56, 8.3, 0.0, 0.0, 1),
 (1.51755, 13.0, 3.6, 1.36, 72.99, 0.57, 8.4, 0.0, 0.11, 1),
 (1.5157100000000001, 12.72, 3.46, 1.56, 73.2, 0.67, 8.09, 0.0, 0.24, 1),
 (1.51763, 12.8, 3.66, 1.27, 73.01, 0.6, 8.56, 0.0, 0.0, 1),
 (1.51589, 12.88, 3.43, 1.4, 73.28, 0.69, 8.05, 0.0, 0.24, 1),
 (1.51748, 12.86, 3.56, 1.27, 73.21, 0.54, 8.38, 0.0, 0.17, 1),
 (1.51763, 12.61, 3.59, 1.31, 73.29, 0.58, 8.5, 0.0, 0.0, 1),
 (1.5176100000000001, 12.81, 3.54, 1.23, 73.24, 0.58, 8.39, 0.0, 0.0, 1),
 (1.5178399999999999, 12.68, 3.67, 1.16, 73.11, 0.61, 8.7, 0.0, 0.0, 1),
 (1.52196, 14.36, 3.85, 0.89, 71.36, 0.15, 9.15, 0.0, 0.0, 1),
 (1.51911, 13.9, 3.73, 1.18, 72.12, 0.06, 8.89, 0.0, 0.0, 1),
 (1.51735, 13.02, 3.54, 1.69, 72.73, 0.54, 8.44, 0.0, 0.07, 1),
 (1.5175, 12.82, 3.55, 1.49, 72.75, 0.54, 8.52, 0.0, 0.19, 1),
 (1.51966, 14.77, 3.75, 0.29, 72.02, 0.03, 9.0, 0.0, 0.0, 1),
 (1.51736, 12.78, 3.62, 1.29, 72.79, 0.59, 8.7, 0.0, 0.0, 1),
 (1.5175100000000001, 12.81, 3.57, 1.35, 73.02, 0.62, 8.59, 0.0, 0.0, 1),
 (1.5172, 13.38, 3.5, 1.15, 72.85, 0.5, 8.43, 0.0, 0.0, 1),
 (1.5176399999999999, 12.98, 3.54, 1.21, 73.0, 0.65, 8.53, 0.0, 0.0, 1),
 (1.51793, 13.21, 3.48, 1.41, 72.64, 0.59, 8.43, 0.0, 0.0, 1),
 (1.51721, 12.87, 3.48, 1.33, 73.04, 0.56, 8.43, 0.0, 0.0, 1),
 (1.51768, 12.56, 3.52, 1.43, 73.15, 0.57, 8.54, 0.0, 0.0, 1),
 (1.5178399999999999, 13.08, 3.49, 1.28, 72.86, 0.6, 8.49, 0.0, 0.0, 1),
 (1.51768, 12.65, 3.56, 1.3, 73.08, 0.61, 8.69, 0.0, 0.14, 1),
 (1.51747, 12.84, 3.5, 1.14, 73.27, 0.56, 8.55, 0.0, 0.0, 1),
 (1.51775, 12.85, 3.48, 1.23, 72.97, 0.61, 8.56, 0.09, 0.22, 1),
 (1.5175299999999998, 12.57, 3.47, 1.38, 73.39, 0.6, 8.55, 0.0, 0.06, 1),
 (1.51783, 12.69, 3.54, 1.34, 72.95, 0.57, 8.75, 0.0, 0.0, 1),
 (1.51567, 13.29, 3.45, 1.21, 72.74, 0.56, 8.57, 0.0, 0.0, 1),
 (1.51909, 13.89, 3.53, 1.32, 71.81, 0.51, 8.78, 0.11, 0.0, 1),
 (1.51797, 12.74, 3.48, 1.35, 72.96, 0.64, 8.68, 0.0, 0.0, 1),
 (1.52213, 14.21, 3.82, 0.47, 71.77, 0.11, 9.57, 0.0, 0.0, 1),
 (1.52213, 14.21, 3.82, 0.47, 71.77, 0.11, 9.57, 0.0, 0.0, 1),
 (1.51793, 12.79, 3.5, 1.12, 73.03, 0.64, 8.77, 0.0, 0.0, 1),
 (1.51755, 12.71, 3.42, 1.2, 73.2, 0.59, 8.64, 0.0, 0.0, 1),
 (1.51779, 13.21, 3.39, 1.33, 72.76, 0.59, 8.59, 0.0, 0.0, 1),
 (1.5221, 13.73, 3.84, 0.72, 71.76, 0.17, 9.74, 0.0, 0.0, 1),
 (1.51786, 12.73, 3.43, 1.19, 72.95, 0.62, 8.76, 0.0, 0.3, 1),
 (1.5190000000000001, 13.49, 3.48, 1.35, 71.95, 0.55, 9.0, 0.0, 0.0, 1),
 (1.5186899999999999, 13.19, 3.37, 1.18, 72.72, 0.57, 8.83, 0.0, 0.16, 1),
 (1.52667, 13.99, 3.7, 0.71, 71.57, 0.02, 9.82, 0.0, 0.1, 1),
 (1.52223, 13.21, 3.77, 0.79, 71.99, 0.13, 10.02, 0.0, 0.0, 1),
 (1.51898, 13.58, 3.35, 1.23, 72.08, 0.59, 8.91, 0.0, 0.0, 1),
 (1.5232, 13.72, 3.72, 0.51, 71.75, 0.09, 10.06, 0.0, 0.16, 1),
 (1.51926, 13.2, 3.33, 1.28, 72.36, 0.6, 9.14, 0.0, 0.11, 1),
 (1.5180799999999999, 13.43, 2.87, 1.19, 72.84, 0.55, 9.03, 0.0, 0.0, 1),
 (1.51837, 13.14, 2.84, 1.28, 72.85, 0.55, 9.07, 0.0, 0.0, 1),
 (1.51778, 13.21, 2.81, 1.29, 72.98, 0.51, 9.02, 0.0, 0.09, 1),
 (1.51769, 12.45, 2.71, 1.29, 73.7, 0.56, 9.06, 0.0, 0.24, 1),
 (1.51215, 12.99, 3.47, 1.12, 72.98, 0.62, 8.35, 0.0, 0.31, 1),
 (1.51824, 12.87, 3.48, 1.29, 72.95, 0.6, 8.43, 0.0, 0.0, 1),
 (1.51754, 13.48, 3.74, 1.17, 72.99, 0.59, 8.03, 0.0, 0.0, 1),
 (1.51754, 13.39, 3.66, 1.19, 72.79, 0.57, 8.27, 0.0, 0.11, 1),
 (1.51905, 13.6, 3.62, 1.11, 72.64, 0.14, 8.76, 0.0, 0.0, 1),
 (1.51977, 13.81, 3.58, 1.32, 71.72, 0.12, 8.67, 0.69, 0.0, 1),
 (1.5217200000000002, 13.51, 3.86, 0.88, 71.79, 0.23, 9.54, 0.0, 0.11, 1),
 (1.52227, 14.17, 3.81, 0.78, 71.35, 0.0, 9.69, 0.0, 0.0, 1),
 (1.5217200000000002, 13.48, 3.74, 0.9, 72.01, 0.18, 9.61, 0.0, 0.07, 1),
 (1.52099, 13.69, 3.59, 1.12, 71.96, 0.09, 9.4, 0.0, 0.0, 1),
 (1.52152, 13.05, 3.65, 0.87, 72.22, 0.19, 9.85, 0.0, 0.17, 1),
 (1.52152, 13.05, 3.65, 0.87, 72.32, 0.19, 9.85, 0.0, 0.17, 1),
 (1.52152, 13.12, 3.58, 0.9, 72.2, 0.23, 9.82, 0.0, 0.16, 1),
 (1.5230000000000001, 13.31, 3.58, 0.82, 71.99, 0.12, 10.17, 0.0, 0.03, 1),
 (1.5157399999999999, 14.86, 3.67, 1.74, 71.87, 0.16, 7.36, 0.0, 0.12, 2),
 (1.5184799999999998, 13.64, 3.87, 1.27, 71.96, 0.54, 8.32, 0.0, 0.32, 2),
 (1.51593, 13.09, 3.59, 1.52, 73.1, 0.67, 7.83, 0.0, 0.0, 2),
 (1.51631, 13.34, 3.57, 1.57, 72.87, 0.61, 7.89, 0.0, 0.0, 2),
 (1.51596, 13.02, 3.56, 1.54, 73.11, 0.72, 7.9, 0.0, 0.0, 2),
 (1.5159, 13.02, 3.58, 1.51, 73.12, 0.69, 7.96, 0.0, 0.0, 2),
 (1.51645, 13.44, 3.61, 1.54, 72.39, 0.66, 8.03, 0.0, 0.0, 2),
 (1.51627, 13.0, 3.58, 1.54, 72.83, 0.61, 8.04, 0.0, 0.0, 2),
 (1.51613, 13.92, 3.52, 1.25, 72.88, 0.37, 7.94, 0.0, 0.14, 2),
 (1.5159, 12.82, 3.52, 1.9, 72.86, 0.69, 7.97, 0.0, 0.0, 2),
 (1.5159200000000002, 12.86, 3.52, 2.12, 72.66, 0.69, 7.97, 0.0, 0.0, 2),
 (1.51593, 13.25, 3.45, 1.43, 73.17, 0.61, 7.86, 0.0, 0.0, 2),
 (1.5164600000000001, 13.41, 3.55, 1.25, 72.81, 0.68, 8.1, 0.0, 0.0, 2),
 (1.51594, 13.09, 3.52, 1.55, 72.87, 0.68, 8.05, 0.0, 0.09, 2),
 (1.51409, 14.25, 3.09, 2.08, 72.28, 1.1, 7.08, 0.0, 0.0, 2),
 (1.51625, 13.36, 3.58, 1.49, 72.72, 0.45, 8.21, 0.0, 0.0, 2),
 (1.51569, 13.24, 3.49, 1.47, 73.25, 0.38, 8.03, 0.0, 0.0, 2),
 (1.51645, 13.4, 3.49, 1.52, 72.65, 0.67, 8.08, 0.0, 0.1, 2),
 (1.5161799999999999, 13.01, 3.5, 1.48, 72.89, 0.6, 8.12, 0.0, 0.0, 2),
 (1.5164, 12.55, 3.48, 1.87, 73.23, 0.63, 8.08, 0.0, 0.09, 2),
 (1.51841, 12.93, 3.74, 1.11, 72.28, 0.64, 8.96, 0.0, 0.22, 2),
 (1.51605, 12.9, 3.44, 1.45, 73.06, 0.44, 8.27, 0.0, 0.0, 2),
 (1.51588, 13.12, 3.41, 1.58, 73.26, 0.07, 8.39, 0.0, 0.19, 2),
 (1.5159, 13.24, 3.34, 1.47, 73.1, 0.39, 8.22, 0.0, 0.0, 2),
 (1.51629, 12.71, 3.33, 1.49, 73.28, 0.67, 8.24, 0.0, 0.0, 2),
 (1.5186, 13.36, 3.43, 1.43, 72.26, 0.51, 8.6, 0.0, 0.0, 2),
 (1.51841, 13.02, 3.62, 1.06, 72.34, 0.64, 9.13, 0.0, 0.15, 2),
 (1.5174299999999998, 12.2, 3.25, 1.16, 73.55, 0.62, 8.9, 0.0, 0.24, 2),
 (1.51689, 12.67, 2.88, 1.71, 73.21, 0.73, 8.54, 0.0, 0.0, 2),
 (1.51811, 12.96, 2.96, 1.43, 72.92, 0.6, 8.79, 0.14, 0.0, 2),
 (1.51655, 12.75, 2.85, 1.44, 73.27, 0.57, 8.79, 0.11, 0.22, 2),
 (1.5173, 12.35, 2.72, 1.63, 72.87, 0.7, 9.23, 0.0, 0.0, 2),
 (1.5182, 12.62, 2.76, 0.83, 73.81, 0.35, 9.42, 0.0, 0.2, 2),
 (1.52725, 13.8, 3.15, 0.66, 70.57, 0.08, 11.64, 0.0, 0.0, 2),
 (1.5241, 13.83, 2.9, 1.17, 71.15, 0.08, 10.79, 0.0, 0.0, 2),
 (1.52475, 11.45, 0.0, 1.88, 72.19, 0.81, 13.24, 0.0, 0.34, 2),
 (1.53125, 10.73, 0.0, 2.1, 69.81, 0.58, 13.3, 3.15, 0.28, 2),
 (1.53393, 12.3, 0.0, 1.0, 70.16, 0.12, 16.19, 0.0, 0.24, 2),
 (1.5222200000000001, 14.43, 0.0, 1.0, 72.67, 0.1, 11.52, 0.0, 0.08, 2),
 (1.5181799999999999, 13.72, 0.0, 0.56, 74.45, 0.0, 10.99, 0.0, 0.0, 2),
 (1.52664, 11.23, 0.0, 0.77, 73.21, 0.0, 14.68, 0.0, 0.0, 2),
 (1.52739, 11.02, 0.0, 0.75, 73.08, 0.0, 14.96, 0.0, 0.0, 2),
 (1.52777, 12.64, 0.0, 0.67, 72.02, 0.06, 14.4, 0.0, 0.0, 2),
 (1.51892, 13.46, 3.83, 1.26, 72.55, 0.57, 8.21, 0.0, 0.14, 2),
 (1.51847, 13.1, 3.97, 1.19, 72.44, 0.6, 8.43, 0.0, 0.0, 2),
 (1.5184600000000001, 13.41, 3.89, 1.33, 72.38, 0.51, 8.28, 0.0, 0.0, 2),
 (1.51829, 13.24, 3.9, 1.41, 72.33, 0.55, 8.31, 0.0, 0.1, 2),
 (1.51708, 13.72, 3.68, 1.81, 72.06, 0.64, 7.88, 0.0, 0.0, 2),
 (1.51673, 13.3, 3.64, 1.53, 72.53, 0.65, 8.03, 0.0, 0.29, 2),
 (1.51652, 13.56, 3.57, 1.47, 72.45, 0.64, 7.96, 0.0, 0.0, 2),
 (1.51844, 13.25, 3.76, 1.32, 72.4, 0.58, 8.42, 0.0, 0.0, 2),
 (1.51663, 12.93, 3.54, 1.62, 72.96, 0.64, 8.03, 0.0, 0.21, 2),
 (1.5168700000000002, 13.23, 3.54, 1.48, 72.84, 0.56, 8.1, 0.0, 0.0, 2),
 (1.5170700000000001, 13.48, 3.48, 1.71, 72.52, 0.62, 7.99, 0.0, 0.0, 2),
 (1.52177, 13.2, 3.68, 1.15, 72.75, 0.54, 8.52, 0.0, 0.0, 2),
 (1.51872, 12.93, 3.66, 1.56, 72.51, 0.58, 8.55, 0.0, 0.12, 2),
 (1.51667, 12.94, 3.61, 1.26, 72.75, 0.56, 8.6, 0.0, 0.0, 2),
 (1.52081, 13.78, 2.28, 1.43, 71.99, 0.49, 9.85, 0.0, 0.17, 2),
 (1.52068, 13.55, 2.09, 1.67, 72.18, 0.53, 9.57, 0.27, 0.17, 2),
 (1.5202, 13.98, 1.35, 1.63, 71.76, 0.39, 10.56, 0.0, 0.18, 2),
 (1.52177, 13.75, 1.01, 1.36, 72.19, 0.33, 11.14, 0.0, 0.0, 2),
 (1.52614, 13.7, 0.0, 1.36, 71.24, 0.19, 13.44, 0.0, 0.1, 2),
 (1.51813, 13.43, 3.98, 1.18, 72.49, 0.58, 8.15, 0.0, 0.0, 2),
 (1.518, 13.71, 3.93, 1.54, 71.81, 0.54, 8.21, 0.0, 0.15, 2),
 (1.51811, 13.33, 3.85, 1.25, 72.78, 0.52, 8.12, 0.0, 0.0, 2),
 (1.51789, 13.19, 3.9, 1.3, 72.33, 0.55, 8.44, 0.0, 0.28, 2),
 (1.51806, 13.0, 3.8, 1.08, 73.07, 0.56, 8.38, 0.0, 0.12, 2),
 (1.51711, 12.89, 3.62, 1.57, 72.96, 0.61, 8.11, 0.0, 0.0, 2),
 (1.51674, 12.79, 3.52, 1.54, 73.36, 0.66, 7.9, 0.0, 0.0, 2),
 (1.51674, 12.87, 3.56, 1.64, 73.14, 0.65, 7.99, 0.0, 0.0, 2),
 (1.5169, 13.33, 3.54, 1.61, 72.54, 0.68, 8.11, 0.0, 0.0, 2),
 (1.51851, 13.2, 3.63, 1.07, 72.83, 0.57, 8.41, 0.09, 0.17, 2),
 (1.51662, 12.85, 3.51, 1.44, 73.01, 0.68, 8.23, 0.06, 0.25, 2),
 (1.51709, 13.0, 3.47, 1.79, 72.72, 0.66, 8.18, 0.0, 0.0, 2),
 (1.5166, 12.99, 3.18, 1.23, 72.97, 0.58, 8.81, 0.0, 0.24, 2),
 (1.51839, 12.85, 3.67, 1.24, 72.57, 0.62, 8.68, 0.0, 0.35, 2),
 (1.51769, 13.65, 3.66, 1.11, 72.77, 0.11, 8.6, 0.0, 0.0, 3),
 (1.5161, 13.33, 3.53, 1.34, 72.67, 0.56, 8.33, 0.0, 0.0, 3),
 (1.5167, 13.24, 3.57, 1.38, 72.7, 0.56, 8.44, 0.0, 0.1, 3),
 (1.51643, 12.16, 3.52, 1.35, 72.89, 0.57, 8.53, 0.0, 0.0, 3),
 (1.51665, 13.14, 3.45, 1.76, 72.48, 0.6, 8.38, 0.0, 0.17, 3),
 (1.5212700000000001, 14.32, 3.9, 0.83, 71.5, 0.0, 9.49, 0.0, 0.0, 3),
 (1.51779, 13.64, 3.65, 0.65, 73.0, 0.06, 8.93, 0.0, 0.0, 3),
 (1.5161, 13.42, 3.4, 1.22, 72.69, 0.59, 8.32, 0.0, 0.0, 3),
 (1.51694, 12.86, 3.58, 1.31, 72.61, 0.61, 8.79, 0.0, 0.0, 3),
 (1.5164600000000001, 13.04, 3.4, 1.26, 73.01, 0.52, 8.58, 0.0, 0.0, 3),
 (1.51655, 13.41, 3.39, 1.28, 72.64, 0.52, 8.65, 0.0, 0.0, 3),
 (1.52121, 14.03, 3.76, 0.58, 71.79, 0.11, 9.65, 0.0, 0.0, 3),
 (1.51776, 13.53, 3.41, 1.52, 72.04, 0.58, 8.79, 0.0, 0.0, 3),
 (1.51796, 13.5, 3.36, 1.63, 71.94, 0.57, 8.81, 0.0, 0.09, 3),
 (1.5183200000000001, 13.33, 3.34, 1.54, 72.14, 0.56, 8.99, 0.0, 0.0, 3),
 (1.51934, 13.64, 3.54, 0.75, 72.65, 0.16, 8.89, 0.15, 0.24, 3),
 (1.52211, 14.19, 3.78, 0.91, 71.36, 0.23, 9.14, 0.0, 0.37, 3),
 (1.51514, 14.01, 2.68, 3.5, 69.89, 1.68, 5.87, 2.2, 0.0, 5),
 (1.51915, 12.73, 1.85, 1.86, 72.69, 0.6, 10.09, 0.0, 0.0, 5),
 (1.5217100000000001, 11.56, 1.88, 1.56, 72.86, 0.47, 11.41, 0.0, 0.0, 5),
 (1.5215100000000001, 11.03, 1.71, 1.56, 73.44, 0.58, 11.62, 0.0, 0.0, 5),
 (1.51969, 12.64, 0.0, 1.65, 73.75, 0.38, 11.53, 0.0, 0.0, 5),
 (1.5166600000000001, 12.86, 0.0, 1.83, 73.88, 0.97, 10.17, 0.0, 0.0, 5),
 (1.51994, 13.27, 0.0, 1.76, 73.03, 0.47, 11.32, 0.0, 0.0, 5),
 (1.52369, 13.44, 0.0, 1.58, 72.22, 0.32, 12.24, 0.0, 0.0, 5),
 (1.51316, 13.02, 0.0, 3.04, 70.48, 6.21, 6.96, 0.0, 0.0, 5),
 (1.51321, 13.0, 0.0, 3.02, 70.7, 6.21, 6.93, 0.0, 0.0, 5),
 (1.52043, 13.38, 0.0, 1.4, 72.25, 0.33, 12.5, 0.0, 0.0, 5),
 (1.5205799999999998, 12.85, 1.61, 2.17, 72.18, 0.76, 9.7, 0.24, 0.51, 5),
 (1.52119, 12.97, 0.33, 1.51, 73.39, 0.13, 11.27, 0.0, 0.28, 5),
 (1.51905, 14.0, 2.39, 1.56, 72.37, 0.0, 9.57, 0.0, 0.0, 6),
 (1.51937, 13.79, 2.41, 1.19, 72.76, 0.0, 9.77, 0.0, 0.0, 6),
 (1.51829, 14.46, 2.24, 1.62, 72.38, 0.0, 9.26, 0.0, 0.0, 6),
 (1.51852, 14.09, 2.19, 1.66, 72.67, 0.0, 9.32, 0.0, 0.0, 6),
 (1.51299, 14.4, 1.74, 1.54, 74.55, 0.0, 7.59, 0.0, 0.0, 6),
 (1.51888, 14.99, 0.78, 1.74, 72.5, 0.0, 9.95, 0.0, 0.0, 6),
 (1.51916, 14.15, 0.0, 2.09, 72.74, 0.0, 10.88, 0.0, 0.0, 6),
 (1.51969, 14.56, 0.0, 0.56, 73.48, 0.0, 11.22, 0.0, 0.0, 6),
 (1.51115, 17.38, 0.0, 0.34, 75.41, 0.0, 6.65, 0.0, 0.0, 6),
 (1.51131, 13.69, 3.2, 1.81, 72.81, 1.76, 5.43, 1.19, 0.0, 7),
 (1.5183799999999998, 14.32, 3.26, 2.22, 71.25, 1.46, 5.79, 1.63, 0.0, 7),
 (1.52315, 13.44, 3.34, 1.23, 72.38, 0.6, 8.83, 0.0, 0.0, 7),
 (1.52247, 14.86, 2.2, 2.06, 70.26, 0.76, 9.76, 0.0, 0.0, 7),
 (1.52365, 15.79, 1.83, 1.31, 70.43, 0.31, 8.61, 1.68, 0.0, 7),
 (1.51613, 13.88, 1.78, 1.79, 73.1, 0.0, 8.67, 0.76, 0.0, 7),
 (1.5160200000000001, 14.85, 0.0, 2.38, 73.28, 0.0, 8.76, 0.64, 0.09, 7),
 (1.51623, 14.2, 0.0, 2.79, 73.46, 0.04, 9.04, 0.4, 0.09, 7),
 (1.51719, 14.75, 0.0, 2.0, 73.02, 0.0, 8.53, 1.59, 0.08, 7),
 (1.51683, 14.56, 0.0, 1.98, 73.29, 0.0, 8.52, 1.57, 0.07, 7),
 (1.51545, 14.14, 0.0, 2.68, 73.39, 0.08, 9.07, 0.61, 0.05, 7),
 (1.51556, 13.87, 0.0, 2.54, 73.23, 0.14, 9.41, 0.81, 0.01, 7),
 (1.5172700000000001, 14.7, 0.0, 2.34, 73.28, 0.0, 8.95, 0.66, 0.0, 7),
 (1.51531, 14.38, 0.0, 2.66, 73.1, 0.04, 9.08, 0.64, 0.0, 7),
 (1.51609, 15.01, 0.0, 2.51, 73.05, 0.05, 8.83, 0.53, 0.0, 7),
 (1.51508, 15.15, 0.0, 2.25, 73.5, 0.0, 8.34, 0.63, 0.0, 7),
 (1.51653, 11.95, 0.0, 1.19, 75.18, 2.7, 8.93, 0.0, 0.0, 7),
 (1.51514, 14.85, 0.0, 2.42, 73.72, 0.0, 8.39, 0.56, 0.0, 7),
 (1.5165799999999998, 14.8, 0.0, 1.99, 73.11, 0.0, 8.28, 1.71, 0.0, 7),
 (1.51617, 14.95, 0.0, 2.27, 73.3, 0.0, 8.71, 0.67, 0.0, 7),
 (1.51732, 14.95, 0.0, 1.8, 72.99, 0.0, 8.61, 1.55, 0.0, 7),
 (1.51645, 14.94, 0.0, 1.87, 73.11, 0.0, 8.67, 1.38, 0.0, 7),
 (1.51831, 14.39, 0.0, 1.82, 72.86, 1.41, 6.47, 2.88, 0.0, 7),
 (1.5164, 14.37, 0.0, 2.74, 72.85, 0.0, 9.45, 0.54, 0.0, 7),
 (1.51623, 14.14, 0.0, 2.88, 72.61, 0.08, 9.18, 1.06, 0.0, 7),
 (1.51685, 14.92, 0.0, 1.99, 73.06, 0.0, 8.4, 1.59, 0.0, 7),
 (1.52065, 14.36, 0.0, 2.02, 73.42, 0.0, 8.44, 1.64, 0.0, 7),
 (1.51651, 14.38, 0.0, 1.94, 73.61, 0.0, 8.48, 1.57, 0.0, 7),
 (1.51711, 14.23, 0.0, 2.08, 73.36, 0.0, 8.62, 1.67, 0.0, 7)]

In [41]:
# Example 3
# The perform the mentioned update
#
%%sql
UPDATE Glass
SET Type = 2
WHERE Fe > 0.2;

SELECT * FROM Glass;

 * sqlite://
24 rows affected.
Done.

[(1.52101, 13.64, 4.49, 1.1, 71.78, 0.06, 8.75, 0.0, 0.0, 1),
 (1.5176100000000001, 13.89, 3.6, 1.36, 72.73, 0.48, 7.83, 0.0, 0.0, 1),
 (1.5161799999999999, 13.53, 3.55, 1.54, 72.99, 0.39, 7.78, 0.0, 0.0, 1),
 (1.51766, 13.21, 3.69, 1.29, 72.61, 0.57, 8.22, 0.0, 0.0, 1),
 (1.51742, 13.27, 3.62, 1.24, 73.08, 0.55, 8.07, 0.0, 0.0, 1),
 (1.51596, 12.79, 3.61, 1.62, 72.97, 0.64, 8.07, 0.0, 0.26, 2),
 (1.5174299999999998, 13.3, 3.6, 1.14, 73.09, 0.58, 8.17, 0.0, 0.0, 1),
 (1.51756, 13.15, 3.61, 1.05, 73.24, 0.57, 8.24, 0.0, 0.0, 1),
 (1.51918, 14.04, 3.58, 1.37, 72.08, 0.56, 8.3, 0.0, 0.0, 1),
 (1.51755, 13.0, 3.6, 1.36, 72.99, 0.57, 8.4, 0.0, 0.11, 1),
 (1.5157100000000001, 12.72, 3.46, 1.56, 73.2, 0.67, 8.09, 0.0, 0.24, 2),
 (1.51763, 12.8, 3.66, 1.27, 73.01, 0.6, 8.56, 0.0, 0.0, 1),
 (1.51589, 12.88, 3.43, 1.4, 73.28, 0.69, 8.05, 0.0, 0.24, 2),
 (1.51748, 12.86, 3.56, 1.27, 73.21, 0.54, 8.38, 0.0, 0.17, 1),
 (1.51763, 12.61, 3.59, 1.31, 73.29, 0.58, 8.5, 0.0, 0.0, 1),
 (1.5176100000000001, 12.81, 3.54, 1.23, 73.24, 0.58, 8.39, 0.0, 0.0, 1),
 (1.5178399999999999, 12.68, 3.67, 1.16, 73.11, 0.61, 8.7, 0.0, 0.0, 1),
 (1.52196, 14.36, 3.85, 0.89, 71.36, 0.15, 9.15, 0.0, 0.0, 1),
 (1.51911, 13.9, 3.73, 1.18, 72.12, 0.06, 8.89, 0.0, 0.0, 1),
 (1.51735, 13.02, 3.54, 1.69, 72.73, 0.54, 8.44, 0.0, 0.07, 1),
 (1.5175, 12.82, 3.55, 1.49, 72.75, 0.54, 8.52, 0.0, 0.19, 1),
 (1.51966, 14.77, 3.75, 0.29, 72.02, 0.03, 9.0, 0.0, 0.0, 1),
 (1.51736, 12.78, 3.62, 1.29, 72.79, 0.59, 8.7, 0.0, 0.0, 1),
 (1.5175100000000001, 12.81, 3.57, 1.35, 73.02, 0.62, 8.59, 0.0, 0.0, 1),
 (1.5172, 13.38, 3.5, 1.15, 72.85, 0.5, 8.43, 0.0, 0.0, 1),
 (1.5176399999999999, 12.98, 3.54, 1.21, 73.0, 0.65, 8.53, 0.0, 0.0, 1),
 (1.51793, 13.21, 3.48, 1.41, 72.64, 0.59, 8.43, 0.0, 0.0, 1),
 (1.51721, 12.87, 3.48, 1.33, 73.04, 0.56, 8.43, 0.0, 0.0, 1),
 (1.51768, 12.56, 3.52, 1.43, 73.15, 0.57, 8.54, 0.0, 0.0, 1),
 (1.5178399999999999, 13.08, 3.49, 1.28, 72.86, 0.6, 8.49, 0.0, 0.0, 1),
 (1.51768, 12.65, 3.56, 1.3, 73.08, 0.61, 8.69, 0.0, 0.14, 1),
 (1.51747, 12.84, 3.5, 1.14, 73.27, 0.56, 8.55, 0.0, 0.0, 1),
 (1.51775, 12.85, 3.48, 1.23, 72.97, 0.61, 8.56, 0.09, 0.22, 2),
 (1.5175299999999998, 12.57, 3.47, 1.38, 73.39, 0.6, 8.55, 0.0, 0.06, 1),
 (1.51783, 12.69, 3.54, 1.34, 72.95, 0.57, 8.75, 0.0, 0.0, 1),
 (1.51567, 13.29, 3.45, 1.21, 72.74, 0.56, 8.57, 0.0, 0.0, 1),
 (1.51909, 13.89, 3.53, 1.32, 71.81, 0.51, 8.78, 0.11, 0.0, 1),
 (1.51797, 12.74, 3.48, 1.35, 72.96, 0.64, 8.68, 0.0, 0.0, 1),
 (1.52213, 14.21, 3.82, 0.47, 71.77, 0.11, 9.57, 0.0, 0.0, 1),
 (1.52213, 14.21, 3.82, 0.47, 71.77, 0.11, 9.57, 0.0, 0.0, 1),
 (1.51793, 12.79, 3.5, 1.12, 73.03, 0.64, 8.77, 0.0, 0.0, 1),
 (1.51755, 12.71, 3.42, 1.2, 73.2, 0.59, 8.64, 0.0, 0.0, 1),
 (1.51779, 13.21, 3.39, 1.33, 72.76, 0.59, 8.59, 0.0, 0.0, 1),
 (1.5221, 13.73, 3.84, 0.72, 71.76, 0.17, 9.74, 0.0, 0.0, 1),
 (1.51786, 12.73, 3.43, 1.19, 72.95, 0.62, 8.76, 0.0, 0.3, 2),
 (1.5190000000000001, 13.49, 3.48, 1.35, 71.95, 0.55, 9.0, 0.0, 0.0, 1),
 (1.5186899999999999, 13.19, 3.37, 1.18, 72.72, 0.57, 8.83, 0.0, 0.16, 1),
 (1.52667, 13.99, 3.7, 0.71, 71.57, 0.02, 9.82, 0.0, 0.1, 1),
 (1.52223, 13.21, 3.77, 0.79, 71.99, 0.13, 10.02, 0.0, 0.0, 1),
 (1.51898, 13.58, 3.35, 1.23, 72.08, 0.59, 8.91, 0.0, 0.0, 1),
 (1.5232, 13.72, 3.72, 0.51, 71.75, 0.09, 10.06, 0.0, 0.16, 1),
 (1.51926, 13.2, 3.33, 1.28, 72.36, 0.6, 9.14, 0.0, 0.11, 1),
 (1.5180799999999999, 13.43, 2.87, 1.19, 72.84, 0.55, 9.03, 0.0, 0.0, 1),
 (1.51837, 13.14, 2.84, 1.28, 72.85, 0.55, 9.07, 0.0, 0.0, 1),
 (1.51778, 13.21, 2.81, 1.29, 72.98, 0.51, 9.02, 0.0, 0.09, 1),
 (1.51769, 12.45, 2.71, 1.29, 73.7, 0.56, 9.06, 0.0, 0.24, 2),
 (1.51215, 12.99, 3.47, 1.12, 72.98, 0.62, 8.35, 0.0, 0.31, 2),
 (1.51824, 12.87, 3.48, 1.29, 72.95, 0.6, 8.43, 0.0, 0.0, 1),
 (1.51754, 13.48, 3.74, 1.17, 72.99, 0.59, 8.03, 0.0, 0.0, 1),
 (1.51754, 13.39, 3.66, 1.19, 72.79, 0.57, 8.27, 0.0, 0.11, 1),
 (1.51905, 13.6, 3.62, 1.11, 72.64, 0.14, 8.76, 0.0, 0.0, 1),
 (1.51977, 13.81, 3.58, 1.32, 71.72, 0.12, 8.67, 0.69, 0.0, 1),
 (1.5217200000000002, 13.51, 3.86, 0.88, 71.79, 0.23, 9.54, 0.0, 0.11, 1),
 (1.52227, 14.17, 3.81, 0.78, 71.35, 0.0, 9.69, 0.0, 0.0, 1),
 (1.5217200000000002, 13.48, 3.74, 0.9, 72.01, 0.18, 9.61, 0.0, 0.07, 1),
 (1.52099, 13.69, 3.59, 1.12, 71.96, 0.09, 9.4, 0.0, 0.0, 1),
 (1.52152, 13.05, 3.65, 0.87, 72.22, 0.19, 9.85, 0.0, 0.17, 1),
 (1.52152, 13.05, 3.65, 0.87, 72.32, 0.19, 9.85, 0.0, 0.17, 1),
 (1.52152, 13.12, 3.58, 0.9, 72.2, 0.23, 9.82, 0.0, 0.16, 1),
 (1.5230000000000001, 13.31, 3.58, 0.82, 71.99, 0.12, 10.17, 0.0, 0.03, 1),
 (1.5157399999999999, 14.86, 3.67, 1.74, 71.87, 0.16, 7.36, 0.0, 0.12, 2),
 (1.5184799999999998, 13.64, 3.87, 1.27, 71.96, 0.54, 8.32, 0.0, 0.32, 2),
 (1.51593, 13.09, 3.59, 1.52, 73.1, 0.67, 7.83, 0.0, 0.0, 2),
 (1.51631, 13.34, 3.57, 1.57, 72.87, 0.61, 7.89, 0.0, 0.0, 2),
 (1.51596, 13.02, 3.56, 1.54, 73.11, 0.72, 7.9, 0.0, 0.0, 2),
 (1.5159, 13.02, 3.58, 1.51, 73.12, 0.69, 7.96, 0.0, 0.0, 2),
 (1.51645, 13.44, 3.61, 1.54, 72.39, 0.66, 8.03, 0.0, 0.0, 2),
 (1.51627, 13.0, 3.58, 1.54, 72.83, 0.61, 8.04, 0.0, 0.0, 2),
 (1.51613, 13.92, 3.52, 1.25, 72.88, 0.37, 7.94, 0.0, 0.14, 2),
 (1.5159, 12.82, 3.52, 1.9, 72.86, 0.69, 7.97, 0.0, 0.0, 2),
 (1.5159200000000002, 12.86, 3.52, 2.12, 72.66, 0.69, 7.97, 0.0, 0.0, 2),
 (1.51593, 13.25, 3.45, 1.43, 73.17, 0.61, 7.86, 0.0, 0.0, 2),
 (1.5164600000000001, 13.41, 3.55, 1.25, 72.81, 0.68, 8.1, 0.0, 0.0, 2),
 (1.51594, 13.09, 3.52, 1.55, 72.87, 0.68, 8.05, 0.0, 0.09, 2),
 (1.51409, 14.25, 3.09, 2.08, 72.28, 1.1, 7.08, 0.0, 0.0, 2),
 (1.51625, 13.36, 3.58, 1.49, 72.72, 0.45, 8.21, 0.0, 0.0, 2),
 (1.51569, 13.24, 3.49, 1.47, 73.25, 0.38, 8.03, 0.0, 0.0, 2),
 (1.51645, 13.4, 3.49, 1.52, 72.65, 0.67, 8.08, 0.0, 0.1, 2),
 (1.5161799999999999, 13.01, 3.5, 1.48, 72.89, 0.6, 8.12, 0.0, 0.0, 2),
 (1.5164, 12.55, 3.48, 1.87, 73.23, 0.63, 8.08, 0.0, 0.09, 2),
 (1.51841, 12.93, 3.74, 1.11, 72.28, 0.64, 8.96, 0.0, 0.22, 2),
 (1.51605, 12.9, 3.44, 1.45, 73.06, 0.44, 8.27, 0.0, 0.0, 2),
 (1.51588, 13.12, 3.41, 1.58, 73.26, 0.07, 8.39, 0.0, 0.19, 2),
 (1.5159, 13.24, 3.34, 1.47, 73.1, 0.39, 8.22, 0.0, 0.0, 2),
 (1.51629, 12.71, 3.33, 1.49, 73.28, 0.67, 8.24, 0.0, 0.0, 2),
 (1.5186, 13.36, 3.43, 1.43, 72.26, 0.51, 8.6, 0.0, 0.0, 2),
 (1.51841, 13.02, 3.62, 1.06, 72.34, 0.64, 9.13, 0.0, 0.15, 2),
 (1.5174299999999998, 12.2, 3.25, 1.16, 73.55, 0.62, 8.9, 0.0, 0.24, 2),
 (1.51689, 12.67, 2.88, 1.71, 73.21, 0.73, 8.54, 0.0, 0.0, 2),
 (1.51811, 12.96, 2.96, 1.43, 72.92, 0.6, 8.79, 0.14, 0.0, 2),
 (1.51655, 12.75, 2.85, 1.44, 73.27, 0.57, 8.79, 0.11, 0.22, 2),
 (1.5173, 12.35, 2.72, 1.63, 72.87, 0.7, 9.23, 0.0, 0.0, 2),
 (1.5182, 12.62, 2.76, 0.83, 73.81, 0.35, 9.42, 0.0, 0.2, 2),
 (1.52725, 13.8, 3.15, 0.66, 70.57, 0.08, 11.64, 0.0, 0.0, 2),
 (1.5241, 13.83, 2.9, 1.17, 71.15, 0.08, 10.79, 0.0, 0.0, 2),
 (1.52475, 11.45, 0.0, 1.88, 72.19, 0.81, 13.24, 0.0, 0.34, 2),
 (1.53125, 10.73, 0.0, 2.1, 69.81, 0.58, 13.3, 3.15, 0.28, 2),
 (1.53393, 12.3, 0.0, 1.0, 70.16, 0.12, 16.19, 0.0, 0.24, 2),
 (1.5222200000000001, 14.43, 0.0, 1.0, 72.67, 0.1, 11.52, 0.0, 0.08, 2),
 (1.5181799999999999, 13.72, 0.0, 0.56, 74.45, 0.0, 10.99, 0.0, 0.0, 2),
 (1.52664, 11.23, 0.0, 0.77, 73.21, 0.0, 14.68, 0.0, 0.0, 2),
 (1.52739, 11.02, 0.0, 0.75, 73.08, 0.0, 14.96, 0.0, 0.0, 2),
 (1.52777, 12.64, 0.0, 0.67, 72.02, 0.06, 14.4, 0.0, 0.0, 2),
 (1.51892, 13.46, 3.83, 1.26, 72.55, 0.57, 8.21, 0.0, 0.14, 2),
 (1.51847, 13.1, 3.97, 1.19, 72.44, 0.6, 8.43, 0.0, 0.0, 2),
 (1.5184600000000001, 13.41, 3.89, 1.33, 72.38, 0.51, 8.28, 0.0, 0.0, 2),
 (1.51829, 13.24, 3.9, 1.41, 72.33, 0.55, 8.31, 0.0, 0.1, 2),
 (1.51708, 13.72, 3.68, 1.81, 72.06, 0.64, 7.88, 0.0, 0.0, 2),
 (1.51673, 13.3, 3.64, 1.53, 72.53, 0.65, 8.03, 0.0, 0.29, 2),
 (1.51652, 13.56, 3.57, 1.47, 72.45, 0.64, 7.96, 0.0, 0.0, 2),
 (1.51844, 13.25, 3.76, 1.32, 72.4, 0.58, 8.42, 0.0, 0.0, 2),
 (1.51663, 12.93, 3.54, 1.62, 72.96, 0.64, 8.03, 0.0, 0.21, 2),
 (1.5168700000000002, 13.23, 3.54, 1.48, 72.84, 0.56, 8.1, 0.0, 0.0, 2),
 (1.5170700000000001, 13.48, 3.48, 1.71, 72.52, 0.62, 7.99, 0.0, 0.0, 2),
 (1.52177, 13.2, 3.68, 1.15, 72.75, 0.54, 8.52, 0.0, 0.0, 2),
 (1.51872, 12.93, 3.66, 1.56, 72.51, 0.58, 8.55, 0.0, 0.12, 2),
 (1.51667, 12.94, 3.61, 1.26, 72.75, 0.56, 8.6, 0.0, 0.0, 2),
 (1.52081, 13.78, 2.28, 1.43, 71.99, 0.49, 9.85, 0.0, 0.17, 2),
 (1.52068, 13.55, 2.09, 1.67, 72.18, 0.53, 9.57, 0.27, 0.17, 2),
 (1.5202, 13.98, 1.35, 1.63, 71.76, 0.39, 10.56, 0.0, 0.18, 2),
 (1.52177, 13.75, 1.01, 1.36, 72.19, 0.33, 11.14, 0.0, 0.0, 2),
 (1.52614, 13.7, 0.0, 1.36, 71.24, 0.19, 13.44, 0.0, 0.1, 2),
 (1.51813, 13.43, 3.98, 1.18, 72.49, 0.58, 8.15, 0.0, 0.0, 2),
 (1.518, 13.71, 3.93, 1.54, 71.81, 0.54, 8.21, 0.0, 0.15, 2),
 (1.51811, 13.33, 3.85, 1.25, 72.78, 0.52, 8.12, 0.0, 0.0, 2),
 (1.51789, 13.19, 3.9, 1.3, 72.33, 0.55, 8.44, 0.0, 0.28, 2),
 (1.51806, 13.0, 3.8, 1.08, 73.07, 0.56, 8.38, 0.0, 0.12, 2),
 (1.51711, 12.89, 3.62, 1.57, 72.96, 0.61, 8.11, 0.0, 0.0, 2),
 (1.51674, 12.79, 3.52, 1.54, 73.36, 0.66, 7.9, 0.0, 0.0, 2),
 (1.51674, 12.87, 3.56, 1.64, 73.14, 0.65, 7.99, 0.0, 0.0, 2),
 (1.5169, 13.33, 3.54, 1.61, 72.54, 0.68, 8.11, 0.0, 0.0, 2),
 (1.51851, 13.2, 3.63, 1.07, 72.83, 0.57, 8.41, 0.09, 0.17, 2),
 (1.51662, 12.85, 3.51, 1.44, 73.01, 0.68, 8.23, 0.06, 0.25, 2),
 (1.51709, 13.0, 3.47, 1.79, 72.72, 0.66, 8.18, 0.0, 0.0, 2),
 (1.5166, 12.99, 3.18, 1.23, 72.97, 0.58, 8.81, 0.0, 0.24, 2),
 (1.51839, 12.85, 3.67, 1.24, 72.57, 0.62, 8.68, 0.0, 0.35, 2),
 (1.51769, 13.65, 3.66, 1.11, 72.77, 0.11, 8.6, 0.0, 0.0, 3),
 (1.5161, 13.33, 3.53, 1.34, 72.67, 0.56, 8.33, 0.0, 0.0, 3),
 (1.5167, 13.24, 3.57, 1.38, 72.7, 0.56, 8.44, 0.0, 0.1, 3),
 (1.51643, 12.16, 3.52, 1.35, 72.89, 0.57, 8.53, 0.0, 0.0, 3),
 (1.51665, 13.14, 3.45, 1.76, 72.48, 0.6, 8.38, 0.0, 0.17, 3),
 (1.5212700000000001, 14.32, 3.9, 0.83, 71.5, 0.0, 9.49, 0.0, 0.0, 3),
 (1.51779, 13.64, 3.65, 0.65, 73.0, 0.06, 8.93, 0.0, 0.0, 3),
 (1.5161, 13.42, 3.4, 1.22, 72.69, 0.59, 8.32, 0.0, 0.0, 3),
 (1.51694, 12.86, 3.58, 1.31, 72.61, 0.61, 8.79, 0.0, 0.0, 3),
 (1.5164600000000001, 13.04, 3.4, 1.26, 73.01, 0.52, 8.58, 0.0, 0.0, 3),
 (1.51655, 13.41, 3.39, 1.28, 72.64, 0.52, 8.65, 0.0, 0.0, 3),
 (1.52121, 14.03, 3.76, 0.58, 71.79, 0.11, 9.65, 0.0, 0.0, 3),
 (1.51776, 13.53, 3.41, 1.52, 72.04, 0.58, 8.79, 0.0, 0.0, 3),
 (1.51796, 13.5, 3.36, 1.63, 71.94, 0.57, 8.81, 0.0, 0.09, 3),
 (1.5183200000000001, 13.33, 3.34, 1.54, 72.14, 0.56, 8.99, 0.0, 0.0, 3),
 (1.51934, 13.64, 3.54, 0.75, 72.65, 0.16, 8.89, 0.15, 0.24, 2),
 (1.52211, 14.19, 3.78, 0.91, 71.36, 0.23, 9.14, 0.0, 0.37, 2),
 (1.51514, 14.01, 2.68, 3.5, 69.89, 1.68, 5.87, 2.2, 0.0, 5),
 (1.51915, 12.73, 1.85, 1.86, 72.69, 0.6, 10.09, 0.0, 0.0, 5),
 (1.5217100000000001, 11.56, 1.88, 1.56, 72.86, 0.47, 11.41, 0.0, 0.0, 5),
 (1.5215100000000001, 11.03, 1.71, 1.56, 73.44, 0.58, 11.62, 0.0, 0.0, 5),
 (1.51969, 12.64, 0.0, 1.65, 73.75, 0.38, 11.53, 0.0, 0.0, 5),
 (1.5166600000000001, 12.86, 0.0, 1.83, 73.88, 0.97, 10.17, 0.0, 0.0, 5),
 (1.51994, 13.27, 0.0, 1.76, 73.03, 0.47, 11.32, 0.0, 0.0, 5),
 (1.52369, 13.44, 0.0, 1.58, 72.22, 0.32, 12.24, 0.0, 0.0, 5),
 (1.51316, 13.02, 0.0, 3.04, 70.48, 6.21, 6.96, 0.0, 0.0, 5),
 (1.51321, 13.0, 0.0, 3.02, 70.7, 6.21, 6.93, 0.0, 0.0, 5),
 (1.52043, 13.38, 0.0, 1.4, 72.25, 0.33, 12.5, 0.0, 0.0, 5),
 (1.5205799999999998, 12.85, 1.61, 2.17, 72.18, 0.76, 9.7, 0.24, 0.51, 2),
 (1.52119, 12.97, 0.33, 1.51, 73.39, 0.13, 11.27, 0.0, 0.28, 2),
 (1.51905, 14.0, 2.39, 1.56, 72.37, 0.0, 9.57, 0.0, 0.0, 6),
 (1.51937, 13.79, 2.41, 1.19, 72.76, 0.0, 9.77, 0.0, 0.0, 6),
 (1.51829, 14.46, 2.24, 1.62, 72.38, 0.0, 9.26, 0.0, 0.0, 6),
 (1.51852, 14.09, 2.19, 1.66, 72.67, 0.0, 9.32, 0.0, 0.0, 6),
 (1.51299, 14.4, 1.74, 1.54, 74.55, 0.0, 7.59, 0.0, 0.0, 6),
 (1.51888, 14.99, 0.78, 1.74, 72.5, 0.0, 9.95, 0.0, 0.0, 6),
 (1.51916, 14.15, 0.0, 2.09, 72.74, 0.0, 10.88, 0.0, 0.0, 6),
 (1.51969, 14.56, 0.0, 0.56, 73.48, 0.0, 11.22, 0.0, 0.0, 6),
 (1.51115, 17.38, 0.0, 0.34, 75.41, 0.0, 6.65, 0.0, 0.0, 6),
 (1.51131, 13.69, 3.2, 1.81, 72.81, 1.76, 5.43, 1.19, 0.0, 7),
 (1.5183799999999998, 14.32, 3.26, 2.22, 71.25, 1.46, 5.79, 1.63, 0.0, 7),
 (1.52315, 13.44, 3.34, 1.23, 72.38, 0.6, 8.83, 0.0, 0.0, 7),
 (1.52247, 14.86, 2.2, 2.06, 70.26, 0.76, 9.76, 0.0, 0.0, 7),
 (1.52365, 15.79, 1.83, 1.31, 70.43, 0.31, 8.61, 1.68, 0.0, 7),
 (1.51613, 13.88, 1.78, 1.79, 73.1, 0.0, 8.67, 0.76, 0.0, 7),
 (1.5160200000000001, 14.85, 0.0, 2.38, 73.28, 0.0, 8.76, 0.64, 0.09, 7),
 (1.51623, 14.2, 0.0, 2.79, 73.46, 0.04, 9.04, 0.4, 0.09, 7),
 (1.51719, 14.75, 0.0, 2.0, 73.02, 0.0, 8.53, 1.59, 0.08, 7),
 (1.51683, 14.56, 0.0, 1.98, 73.29, 0.0, 8.52, 1.57, 0.07, 7),
 (1.51545, 14.14, 0.0, 2.68, 73.39, 0.08, 9.07, 0.61, 0.05, 7),
 (1.51556, 13.87, 0.0, 2.54, 73.23, 0.14, 9.41, 0.81, 0.01, 7),
 (1.5172700000000001, 14.7, 0.0, 2.34, 73.28, 0.0, 8.95, 0.66, 0.0, 7),
 (1.51531, 14.38, 0.0, 2.66, 73.1, 0.04, 9.08, 0.64, 0.0, 7),
 (1.51609, 15.01, 0.0, 2.51, 73.05, 0.05, 8.83, 0.53, 0.0, 7),
 (1.51508, 15.15, 0.0, 2.25, 73.5, 0.0, 8.34, 0.63, 0.0, 7),
 (1.51653, 11.95, 0.0, 1.19, 75.18, 2.7, 8.93, 0.0, 0.0, 7),
 (1.51514, 14.85, 0.0, 2.42, 73.72, 0.0, 8.39, 0.56, 0.0, 7),
 (1.5165799999999998, 14.8, 0.0, 1.99, 73.11, 0.0, 8.28, 1.71, 0.0, 7),
 (1.51617, 14.95, 0.0, 2.27, 73.3, 0.0, 8.71, 0.67, 0.0, 7),
 (1.51732, 14.95, 0.0, 1.8, 72.99, 0.0, 8.61, 1.55, 0.0, 7),
 (1.51645, 14.94, 0.0, 1.87, 73.11, 0.0, 8.67, 1.38, 0.0, 7),
 (1.51831, 14.39, 0.0, 1.82, 72.86, 1.41, 6.47, 2.88, 0.0, 7),
 (1.5164, 14.37, 0.0, 2.74, 72.85, 0.0, 9.45, 0.54, 0.0, 7),
 (1.51623, 14.14, 0.0, 2.88, 72.61, 0.08, 9.18, 1.06, 0.0, 7),
 (1.51685, 14.92, 0.0, 1.99, 73.06, 0.0, 8.4, 1.59, 0.0, 7),
 (1.52065, 14.36, 0.0, 2.02, 73.42, 0.0, 8.44, 1.64, 0.0, 7),
 (1.51651, 14.38, 0.0, 1.94, 73.61, 0.0, 8.48, 1.57, 0.0, 7),
 (1.51711, 14.23, 0.0, 2.08, 73.36, 0.0, 8.62, 1.67, 0.0, 7)]

### <font color="green">1.5 Challenges</font>

In [54]:
# Challenge 1
# Let's update Angola with National Fugitives = 2, Wanted Fugitives = 2
# and 0 Possible Hosted Fugitives / Captured Fugitives
# 
%%sql
UPDATE Interpol SET "National Fugitives"=2, "Wanted Fugitives"=2 ,"Possible Hosted Fugitives / Captured Fugitives"=0;

 * sqlite://
82 rows affected.

[]

In [55]:
# Challenge 2
# Update Glass records with Na > 14 to have Type 3 
#
%%sql
UPDATE glass SET "NA"=3 WHERE "NA">14;

 * sqlite://
44 rows affected.

[]

In [ ]:
# Challenge 3
# Update Treatment records with id > 41 to have treatment = "treated"
# 
%%sql
UPDATE glass SET ""

## 1.6 Updating using value from another column

In [56]:
# Example 
# From our Interpol table, lets update National Fugitives = 0 to 
# have the values of its Wanted fugitives.
#
%%sql
UPDATE Interpol
set "National Fugitives" = Interpol."Wanted Fugitives"
where "National Fugitives" = 0;

SELECT * FROM Interpol;

 * sqlite://
0 rows affected.
Done.

[('Albania', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 2, 2, 0, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 2, 2, 0, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Belarus', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Belize', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Bolivia', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif'),
 ('Botswana', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/b/bw.gif'),
 ('Brazil', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/b/br.gif'),
 ('Cambodia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Canada', 2, 2, 0, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('Cayman Islands', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/k/ky.gif'),
 ('Chile', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/cl.gif'),
 ('Colombia', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Congo', 2, 2, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/c/cg.gif'),
 ('Costa Rica', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cr.gif'),
 ('Croatia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Curaçao', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cw.gif'),
 ('Czech Republic', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Denmark', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Dominican Republic', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/d/do.gif'),
 ('Ecuador', 2, 2, 0, 'South America', 'http://www.worldatlas.com/webimage/flags/countrys/zzzflags/eclarge.jpg'),
 ('El Salvador', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/s/sv.gif'),
 ('Estonia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Finland', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('France', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('Germany', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Honduras', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/h/hn.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('India', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Indonesia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Ireland', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Italy', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Kenya', 2, 2, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/k/ke.gif'),
 ('Lesotho', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/l/ls.gif'),
 ('Lithuania', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Macedonia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Mali', 2, 2, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/m/ml.gif'),
 ('Malta', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Mexico', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Montenegro', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Morocco', 2, 2, 0, 'Northern Africa', 'http://www.crwflags.com/fotw/images/m/ma.gif'),
 ('Mozambique', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/m/mz.gif'),
 ('Namibia', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/n/na.gif'),
 ('New Zealand', 2, 2, 0, 'Oceania', 'http://www.crwflags.com/fotw/images/n/nz.gif'),
 ('Nicaragua', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/n/ni.gif'),
 ('Norway', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Pakistan', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Panama', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/p/pa.gif'),
 ('Paraguay', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/py.gif'),
 ('Peru', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/pe.gif'),
 ('Poland', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Qatar', 2, 2, 0, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Romania', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Russia', 2, 2, 0, 'Europe, Asia', 'http://www.crwflags.com/fotw/images/r/ru.gif'),
 ('Serbia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Somalia', 2, 2, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/s/so.gif'),
 ('South Africa', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif'),
 ('Spain', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Swaziland', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/s/sz.gif'),
 ('Sweden', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('Tanzania', 2, 2, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif'),
 ('The Netherlands', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Turkey', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Ukraine', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('United Kingdom', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif'),
 ('United States', 2, 2, 0, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif'),
 ('Uruguay', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('Venezuela', 2, 2, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Zambia', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Zimbabwe', 2, 2, 0, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif'),
 ('Uganda', 2, 2, 0, 'Sub Saharan Africa', 'https://www.crwflags.com/art/countries/uganda.gif'),
 ('Tanzania', 2, 2, 0, 'Sub Saharan Africa', 'https://www.crwflags.com/art/countries/tanzania.gif'),
 ('Botswana', 2, 2, 0, 'Sub Saharan Africa', 'https://www.crwflags.com/art/countries/botswana.gif'),
 ('Sudan', 2, 2, 0, 'Sub Saharan Africa', 'https://www.crwflags.com/art/countries/sudan.gif')]

### <font color="green">1.6 Challenges</font>

In [59]:
with open('./sample_data/Interpol.csv') as f:
  Inter=pd.read_csv(f,index_col=0,encoding='utf-8')

In [61]:
%sql DROP TABLE if EXISTS Inter;
%sql PERSIST Inter;

 * sqlite://
Done.
 * sqlite://

'Persisted inter'

In [62]:
# Challenge 
# From our Interpol table, we will need to update National Fugitives = 0 with
# National Fugitives the sum of Wanted Fugitives and Possible Hosted Fugitives / Captured Fugitives
#
%%sql
UPDATE Inter SET "National Fugitives"=(Inter."Wanted Fugitives" + Inter."Possible Hosted Fugitives / Captured Fugitives") WHERE "National Fugitives"=0;

 * sqlite://
28 rows affected.

[]